name: æ›´æ–°ç¬”è®°ğŸ“’
# è§¦å‘æ¡ä»¶ä¸Šä¼ ä»£ç 
on: [push]
# ä»»åŠ¡
jobs:                   
  # ä»»åŠ¡ç¼–å·è‡ªå®šä¹‰
  job3: 
    # è¿è¡Œç¯å¢ƒ(ubuntu-latest, ubuntu-18.04, or ubuntu-16.04, windows-latest, windows-2019, or windows-2016, macOS-latest or macOS-10.14)
    runs-on: ubuntu-latest
    # è¿è¡Œæ­¥éª¤
    steps:
    # åˆå§‹åŒ–nodeç¯å¢ƒ
    - uses: actions/checkout@master
    # |å¯ä»¥æ‰§è¡Œå¤šè¡Œå‘½ä»¤
    - run: |
        # æŸ¥çœ‹nodeç‰ˆæœ¬
        node -v 
        npm install
        npm run doc:build
        npm run doc:deploy
